name: Simulator tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: "17 * * * *" # Hourly
  workflow_dispatch:
    inputs:
      run_on_ghrunners:
        description: "Also run on GitHub-hosted runners"
        required: false
        type: boolean

jobs:
  test:
    runs-on: namespace-profile-macos-with-caching
    steps:
      - uses: actions/checkout@v4

      - uses: namespacelabs/nscloud-cache-action@kirill/xcode
        with:
          cache: xcode

      - name: Wait for simulators
        run: /opt/powertoys/macos/wait_simulators.sh

      - uses: Wandalen/wretry.action@master
        with: # iOS tests are flaky for no good reason
          command: |
            xcodebuild test -scheme ios-demo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5'
          attempt_limit: 5
          attempt_delay: 30000


  test-ghrunners:
    runs-on: macos-14
    if: inputs.run_on_ghrunners
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app
          xcodebuild test -scheme ios-demo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -quiet
